#############################################################################
# Makefile for building: bin/Gp3A16
# Generated by qmake (2.01a) (Qt 4.8.3) on: mer. janv. 9 20:06:16 2013
# Project:  Gp3A16.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Gp3A16.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Ibin
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lsfml-audio -lsfml-system -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Ball.cpp \
		src/Block.cpp \
		src/GameScene.cpp \
		src/gameSpace.cpp \
		src/GameView.cpp \
		src/gestWindow.cpp \
		src/main.cpp \
		src/mainWindow.cpp \
		src/Stick.cpp \
		src/menu.cpp bin/moc_Ball.cpp \
		bin/moc_gameSpace.cpp \
		bin/moc_GameView.cpp \
		bin/moc_gestWindow.cpp \
		bin/moc_mainWindow.cpp \
		bin/moc_menu.cpp
OBJECTS       = Ball.o \
		Block.o \
		GameScene.o \
		gameSpace.o \
		GameView.o \
		gestWindow.o \
		main.o \
		mainWindow.o \
		Stick.o \
		menu.o \
		moc_Ball.o \
		moc_gameSpace.o \
		moc_GameView.o \
		moc_gestWindow.o \
		moc_mainWindow.o \
		moc_menu.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Gp3A16.pro
QMAKE_TARGET  = Gp3A16
DESTDIR       = bin/
TARGET        = bin/Gp3A16

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gp3A16.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Gp3A16.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Gp3A16.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Gp3A161.0.0 || $(MKDIR) .tmp/Gp3A161.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Gp3A161.0.0/ && $(COPY_FILE) --parents src/Ball.h src/Block.h src/GameScene.h src/gameSpace.h src/GameView.h src/gestWindow.h src/mainWindow.h src/Stick.h src/menu.h .tmp/Gp3A161.0.0/ && $(COPY_FILE) --parents src/Ball.cpp src/Block.cpp src/GameScene.cpp src/gameSpace.cpp src/GameView.cpp src/gestWindow.cpp src/main.cpp src/mainWindow.cpp src/Stick.cpp src/menu.cpp .tmp/Gp3A161.0.0/ && (cd `dirname .tmp/Gp3A161.0.0` && $(TAR) Gp3A161.0.0.tar Gp3A161.0.0 && $(COMPRESS) Gp3A161.0.0.tar) && $(MOVE) `dirname .tmp/Gp3A161.0.0`/Gp3A161.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Gp3A161.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: bin/moc_Ball.cpp bin/moc_gameSpace.cpp bin/moc_GameView.cpp bin/moc_gestWindow.cpp bin/moc_mainWindow.cpp bin/moc_menu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/moc_Ball.cpp bin/moc_gameSpace.cpp bin/moc_GameView.cpp bin/moc_gestWindow.cpp bin/moc_mainWindow.cpp bin/moc_menu.cpp
bin/moc_Ball.cpp: src/Ball.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/Ball.h -o bin/moc_Ball.cpp

bin/moc_gameSpace.cpp: src/GameView.h \
		src/GameScene.h \
		src/Ball.h \
		src/Stick.h \
		src/Block.h \
		src/mainWindow.h \
		src/gestWindow.h \
		src/menu.h \
		src/gameSpace.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gameSpace.h -o bin/moc_gameSpace.cpp

bin/moc_GameView.cpp: src/GameScene.h \
		src/Ball.h \
		src/Stick.h \
		src/Block.h \
		src/GameView.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/GameView.h -o bin/moc_GameView.cpp

bin/moc_gestWindow.cpp: src/gestWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gestWindow.h -o bin/moc_gestWindow.cpp

bin/moc_mainWindow.cpp: src/gestWindow.h \
		src/menu.h \
		src/mainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainWindow.h -o bin/moc_mainWindow.cpp

bin/moc_menu.cpp: src/menu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/menu.h -o bin/moc_menu.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Ball.o: src/Ball.cpp src/Ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ball.o src/Ball.cpp

Block.o: src/Block.cpp src/Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Block.o src/Block.cpp

GameScene.o: src/GameScene.cpp src/GameScene.h \
		src/Ball.h \
		src/Block.h \
		src/Stick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameScene.o src/GameScene.cpp

gameSpace.o: src/gameSpace.cpp src/gameSpace.h \
		src/GameView.h \
		src/GameScene.h \
		src/Ball.h \
		src/Stick.h \
		src/Block.h \
		src/mainWindow.h \
		src/gestWindow.h \
		src/menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameSpace.o src/gameSpace.cpp

GameView.o: src/GameView.cpp src/GameView.h \
		src/GameScene.h \
		src/Ball.h \
		src/Stick.h \
		src/Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameView.o src/GameView.cpp

gestWindow.o: src/gestWindow.cpp src/gestWindow.h \
		src/mainWindow.h \
		src/menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gestWindow.o src/gestWindow.cpp

main.o: src/main.cpp src/mainWindow.h \
		src/gestWindow.h \
		src/menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainWindow.o: src/mainWindow.cpp src/mainWindow.h \
		src/gestWindow.h \
		src/menu.h \
		src/gameSpace.h \
		src/GameView.h \
		src/GameScene.h \
		src/Ball.h \
		src/Stick.h \
		src/Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o src/mainWindow.cpp

Stick.o: src/Stick.cpp src/Stick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stick.o src/Stick.cpp

menu.o: src/menu.cpp src/menu.h \
		src/mainWindow.h \
		src/gestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o src/menu.cpp

moc_Ball.o: bin/moc_Ball.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Ball.o bin/moc_Ball.cpp

moc_gameSpace.o: bin/moc_gameSpace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameSpace.o bin/moc_gameSpace.cpp

moc_GameView.o: bin/moc_GameView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameView.o bin/moc_GameView.cpp

moc_gestWindow.o: bin/moc_gestWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gestWindow.o bin/moc_gestWindow.cpp

moc_mainWindow.o: bin/moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o bin/moc_mainWindow.cpp

moc_menu.o: bin/moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu.o bin/moc_menu.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

